# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zernike.ui'
#
# Created: Tue Mar  4 19:13:52 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(502, 382)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 311))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.astigyMin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.astigyMin.setMinimum(-100.0)
        self.astigyMin.setMaximum(100.0)
        self.astigyMin.setProperty("value", -10.0)
        self.astigyMin.setObjectName(_fromUtf8("astigyMin"))
        self.gridLayout.addWidget(self.astigyMin, 2, 2, 1, 1)
        self.trefoilpMin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.trefoilpMin.setMinimum(-100.0)
        self.trefoilpMin.setMaximum(100.0)
        self.trefoilpMin.setProperty("value", -10.0)
        self.trefoilpMin.setObjectName(_fromUtf8("trefoilpMin"))
        self.gridLayout.addWidget(self.trefoilpMin, 6, 2, 1, 1)
        self.defocusMax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.defocusMax.setMinimum(-100.0)
        self.defocusMax.setMaximum(100.0)
        self.defocusMax.setProperty("value", 10.0)
        self.defocusMax.setObjectName(_fromUtf8("defocusMax"))
        self.gridLayout.addWidget(self.defocusMax, 0, 4, 1, 1)
        self.astigySlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.astigySlider.setProperty("value", 50)
        self.astigySlider.setOrientation(QtCore.Qt.Horizontal)
        self.astigySlider.setInvertedAppearance(False)
        self.astigySlider.setInvertedControls(False)
        self.astigySlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.astigySlider.setObjectName(_fromUtf8("astigySlider"))
        self.gridLayout.addWidget(self.astigySlider, 2, 3, 1, 1)
        self.comamCheck = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.comamCheck.setObjectName(_fromUtf8("comamCheck"))
        self.gridLayout.addWidget(self.comamCheck, 3, 1, 1, 1)
        self.comamSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.comamSlider.setProperty("value", 50)
        self.comamSlider.setOrientation(QtCore.Qt.Horizontal)
        self.comamSlider.setInvertedAppearance(False)
        self.comamSlider.setInvertedControls(False)
        self.comamSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.comamSlider.setObjectName(_fromUtf8("comamSlider"))
        self.gridLayout.addWidget(self.comamSlider, 3, 3, 1, 1)
        self.astigxMax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.astigxMax.setMinimum(-100.0)
        self.astigxMax.setMaximum(100.0)
        self.astigxMax.setProperty("value", 10.0)
        self.astigxMax.setObjectName(_fromUtf8("astigxMax"))
        self.gridLayout.addWidget(self.astigxMax, 1, 4, 1, 1)
        self.comapCheck = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.comapCheck.setObjectName(_fromUtf8("comapCheck"))
        self.gridLayout.addWidget(self.comapCheck, 4, 1, 1, 1)
        self.trefoilpMax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.trefoilpMax.setMinimum(-100.0)
        self.trefoilpMax.setMaximum(100.0)
        self.trefoilpMax.setProperty("value", 10.0)
        self.trefoilpMax.setObjectName(_fromUtf8("trefoilpMax"))
        self.gridLayout.addWidget(self.trefoilpMax, 6, 4, 1, 1)
        self.astigyCheck = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.astigyCheck.setObjectName(_fromUtf8("astigyCheck"))
        self.gridLayout.addWidget(self.astigyCheck, 2, 1, 1, 1)
        self.astigyMax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.astigyMax.setMinimum(-100.0)
        self.astigyMax.setMaximum(100.0)
        self.astigyMax.setProperty("value", 10.0)
        self.astigyMax.setObjectName(_fromUtf8("astigyMax"))
        self.gridLayout.addWidget(self.astigyMax, 2, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.defocusCheck = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.defocusCheck.setObjectName(_fromUtf8("defocusCheck"))
        self.gridLayout.addWidget(self.defocusCheck, 0, 1, 1, 1)
        self.trefoilmCheck = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.trefoilmCheck.setObjectName(_fromUtf8("trefoilmCheck"))
        self.gridLayout.addWidget(self.trefoilmCheck, 5, 1, 1, 1)
        self.trefoilmMin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.trefoilmMin.setMinimum(-100.0)
        self.trefoilmMin.setMaximum(100.0)
        self.trefoilmMin.setProperty("value", -10.0)
        self.trefoilmMin.setObjectName(_fromUtf8("trefoilmMin"))
        self.gridLayout.addWidget(self.trefoilmMin, 5, 2, 1, 1)
        self.defocusSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.defocusSlider.setProperty("value", 50)
        self.defocusSlider.setOrientation(QtCore.Qt.Horizontal)
        self.defocusSlider.setInvertedAppearance(False)
        self.defocusSlider.setInvertedControls(False)
        self.defocusSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.defocusSlider.setObjectName(_fromUtf8("defocusSlider"))
        self.gridLayout.addWidget(self.defocusSlider, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.astigxSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.astigxSlider.setProperty("value", 50)
        self.astigxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.astigxSlider.setInvertedAppearance(False)
        self.astigxSlider.setInvertedControls(False)
        self.astigxSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.astigxSlider.setObjectName(_fromUtf8("astigxSlider"))
        self.gridLayout.addWidget(self.astigxSlider, 1, 3, 1, 1)
        self.comapSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.comapSlider.setProperty("value", 50)
        self.comapSlider.setOrientation(QtCore.Qt.Horizontal)
        self.comapSlider.setInvertedAppearance(False)
        self.comapSlider.setInvertedControls(False)
        self.comapSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.comapSlider.setObjectName(_fromUtf8("comapSlider"))
        self.gridLayout.addWidget(self.comapSlider, 4, 3, 1, 1)
        self.trefoilpSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.trefoilpSlider.setProperty("value", 50)
        self.trefoilpSlider.setOrientation(QtCore.Qt.Horizontal)
        self.trefoilpSlider.setInvertedAppearance(False)
        self.trefoilpSlider.setInvertedControls(False)
        self.trefoilpSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.trefoilpSlider.setObjectName(_fromUtf8("trefoilpSlider"))
        self.gridLayout.addWidget(self.trefoilpSlider, 6, 3, 1, 1)
        self.defocusMin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.defocusMin.setMinimum(-100.0)
        self.defocusMin.setMaximum(100.0)
        self.defocusMin.setProperty("value", -10.0)
        self.defocusMin.setObjectName(_fromUtf8("defocusMin"))
        self.gridLayout.addWidget(self.defocusMin, 0, 2, 1, 1)
        self.trefoilmSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.trefoilmSlider.setProperty("value", 50)
        self.trefoilmSlider.setOrientation(QtCore.Qt.Horizontal)
        self.trefoilmSlider.setInvertedAppearance(False)
        self.trefoilmSlider.setInvertedControls(False)
        self.trefoilmSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.trefoilmSlider.setObjectName(_fromUtf8("trefoilmSlider"))
        self.gridLayout.addWidget(self.trefoilmSlider, 5, 3, 1, 1)
        self.astigxMin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.astigxMin.setMinimum(-100.0)
        self.astigxMin.setMaximum(100.0)
        self.astigxMin.setProperty("value", -10.0)
        self.astigxMin.setObjectName(_fromUtf8("astigxMin"))
        self.gridLayout.addWidget(self.astigxMin, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.comamMin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.comamMin.setMinimum(-100.0)
        self.comamMin.setMaximum(100.0)
        self.comamMin.setProperty("value", -10.0)
        self.comamMin.setObjectName(_fromUtf8("comamMin"))
        self.gridLayout.addWidget(self.comamMin, 3, 2, 1, 1)
        self.comamMax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.comamMax.setMinimum(-100.0)
        self.comamMax.setMaximum(100.0)
        self.comamMax.setProperty("value", 10.0)
        self.comamMax.setObjectName(_fromUtf8("comamMax"))
        self.gridLayout.addWidget(self.comamMax, 3, 4, 1, 1)
        self.astigxCheck = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.astigxCheck.setObjectName(_fromUtf8("astigxCheck"))
        self.gridLayout.addWidget(self.astigxCheck, 1, 1, 1, 1)
        self.comapMin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.comapMin.setMinimum(-100.0)
        self.comapMin.setMaximum(100.0)
        self.comapMin.setProperty("value", -10.0)
        self.comapMin.setObjectName(_fromUtf8("comapMin"))
        self.gridLayout.addWidget(self.comapMin, 4, 2, 1, 1)
        self.comapMax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.comapMax.setMinimum(-100.0)
        self.comapMax.setMaximum(100.0)
        self.comapMax.setProperty("value", 10.0)
        self.comapMax.setObjectName(_fromUtf8("comapMax"))
        self.gridLayout.addWidget(self.comapMax, 4, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.trefoilpCheck = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.trefoilpCheck.setObjectName(_fromUtf8("trefoilpCheck"))
        self.gridLayout.addWidget(self.trefoilpCheck, 6, 1, 1, 1)
        self.trefoilmMax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.trefoilmMax.setMinimum(-100.0)
        self.trefoilmMax.setMaximum(100.0)
        self.trefoilmMax.setProperty("value", 10.0)
        self.trefoilmMax.setObjectName(_fromUtf8("trefoilmMax"))
        self.gridLayout.addWidget(self.trefoilmMax, 5, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.sphericalCheck = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.sphericalCheck.setObjectName(_fromUtf8("sphericalCheck"))
        self.gridLayout.addWidget(self.sphericalCheck, 7, 1, 1, 1)
        self.sphericalMin = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sphericalMin.setMinimum(-100.0)
        self.sphericalMin.setMaximum(100.0)
        self.sphericalMin.setProperty("value", -10.0)
        self.sphericalMin.setObjectName(_fromUtf8("sphericalMin"))
        self.gridLayout.addWidget(self.sphericalMin, 7, 2, 1, 1)
        self.sphericalSlider = QtGui.QSlider(self.verticalLayoutWidget)
        self.sphericalSlider.setProperty("value", 50)
        self.sphericalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sphericalSlider.setInvertedAppearance(False)
        self.sphericalSlider.setInvertedControls(False)
        self.sphericalSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sphericalSlider.setObjectName(_fromUtf8("sphericalSlider"))
        self.gridLayout.addWidget(self.sphericalSlider, 7, 3, 1, 1)
        self.sphericalMax = QtGui.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sphericalMax.setMinimum(-100.0)
        self.sphericalMax.setMaximum(100.0)
        self.sphericalMax.setProperty("value", 10.0)
        self.sphericalMax.setObjectName(_fromUtf8("sphericalMax"))
        self.gridLayout.addWidget(self.sphericalMax, 7, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fitButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.fitButton.setObjectName(_fromUtf8("fitButton"))
        self.horizontalLayout_2.addWidget(self.fitButton)
        self.applyButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.applyButton.setObjectName(_fromUtf8("applyButton"))
        self.horizontalLayout_2.addWidget(self.applyButton)
        self.saveButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.defocusSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.applyButton.click)
        QtCore.QObject.connect(self.astigxSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.applyButton.click)
        QtCore.QObject.connect(self.astigySlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.applyButton.click)
        QtCore.QObject.connect(self.comamSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.applyButton.click)
        QtCore.QObject.connect(self.comapSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.applyButton.click)
        QtCore.QObject.connect(self.trefoilmSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.applyButton.click)
        QtCore.QObject.connect(self.trefoilpSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.applyButton.click)
        QtCore.QObject.connect(self.sphericalSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.applyButton.click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.comamCheck.setToolTip(QtGui.QApplication.translate("Form", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.comapCheck.setToolTip(QtGui.QApplication.translate("Form", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.astigyCheck.setToolTip(QtGui.QApplication.translate("Form", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Z<sub>2,0</sub> defocus", None, QtGui.QApplication.UnicodeUTF8))
        self.defocusCheck.setToolTip(QtGui.QApplication.translate("Form", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.trefoilmCheck.setToolTip(QtGui.QApplication.translate("Form", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Z<sub>3,-3</sub> trefoil", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Z<sub>2,-2</sub> astigmatism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Z<sub>3,-1</sub> coma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Z<sub>3,3</sub> trefoil", None, QtGui.QApplication.UnicodeUTF8))
        self.astigxCheck.setToolTip(QtGui.QApplication.translate("Form", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Z<sub>2,2</sub> astigmatism", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Z<sub>3,1</sub> coma", None, QtGui.QApplication.UnicodeUTF8))
        self.trefoilpCheck.setToolTip(QtGui.QApplication.translate("Form", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Z<sub>4,0</sub> spherical", None, QtGui.QApplication.UnicodeUTF8))
        self.sphericalCheck.setToolTip(QtGui.QApplication.translate("Form", "fit", None, QtGui.QApplication.UnicodeUTF8))
        self.fitButton.setText(QtGui.QApplication.translate("Form", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("Form", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))

